- title: "Accessory dwelling unit (ADU)"
  route: "accessory_dwelling_unit"
  description: "Description of Accessory dwelling unit (ADU)"
- title: "Building Code"
  route: "building_code"
  description: "Description of Building Code"
- title: "Building department process"
  route: "building_department_process"
  description: "Description of Building department process"
- title: "By-right affordable housing"
  route: "by_right_affordable_housing"
  description: "Description of By-right affordable housing"
- title: "By-right shelter conversion"
  route: "by_right_shelter_conversion"
  description: "Description of By-right shelter conversion"
- title: "Clear and objective standards; alternative discretionary review"
  route: "clear_and_objective_standards"
  description: "Description of Clear and objective standards; alternative discretionary review"
- title: "Final engineering review"
  route: "final_engineering_review"
  description: "Description of Final engineering review"
- title: "Land divisions, other than a middle housing land division"
  route: "land_divisions"
  description: "Description of Land divisions, other than a middle housing land division"
- title: "Land use process, permitting, or procedure"
  route: "land_use_processes"
  description: "Description of Land use process, permitting, or procedure"
- title: "Mandatory Adjustments/Flexibility to Development and Design Standards"
  route: "mandatory_adjustments"
  description: "Description of Mandatory Adjustments/Flexibility to Development and Design Standards"
- title: "Manufactured and prefabricated homes and parks"
  route: "manufactured_and_prefab_homes_and_parks"
  description: "Description of Manufactured and prefabricated homes and parks"
- title: "Middle housing, including middle housing land division"
  route: "middle_housing"
  description: "Description of Middle housing, including middle housing land division"
- title: "Moratoria"
  route: "moratoria"
  description: "Description of Moratoria"
- title: "Residential design standards"
  route: "residential_design_standards"
  description: "Description of Residential design standards"
- title: "Residential homes and facilities"
  route: "residential_homes_and_facilities"
  description: "Description of Residential homes and facilities"
- title: "Single room occupancies (SRO)"
  route: "single_room_occupancies"
  description: "Description of Single room occupancies (SRO)"
- title: "State model housing ordinances"
  route: "state_model_housing_ordinances"
  description: "Description of State model housing ordinances"
- title: "Other law not listed here"
  route: "other"
  description: "Description of Other law not listed here"