- title: "Accessory Dwelling Units (ADU)"
  route: "accessory_dwelling_unit"
  description: "Cities and counties above 2,500 population must allow accessory dwelling units (ADUs) in detached single-unit residential zones"
  tags:
    - "Cities with a population of 2,500 or greater"
    - "Cities and urban unincorporated communities in Tillamook County"
    - "Counties with a population of 15,000 or greater"
    - "Within urban growth boundaries"
- title: "Clear and Objective Standards; Alternative Discretionary Review"
  route: "clear_and_objective_standards"
  description: "In development. Coming soon."
  tags:
- title: "By-right affordable housing"
  route: "by_right_affordable_housing"
  description: "In development. Coming soon."
  tags:
- title: "Land use process, permitting, or procedure"
  route: "land_use_processes"
  description: "In development. Coming soon."
- title: "Mandatory Adjustments; Flexibility to Development and Design Standards"
  route: "mandatory_adjustments"
  description: "Requires cities to grant adjustments to specific development & design standards for housing development meeting certain conditions."
  tags:
    - "All cities"
    - "Within urban growth boundaries"
- title: "Manufactured and prefabricated homes and parks"
  route: "manufactured_and_prefab_homes_and_parks"
  description: "Local governments must allow manufactured homes and prefabricated structures, including parks, on certain lands zoned for residential use"
  tags:
    - "All cities"
    - "All counties"
    - "Within urban growth boundaries"
- title: "Middle housing"
  route: "middle_housing"
  description: "Local governments must allow middle housing and land divisions on lands zoned for residential use"
  tags:
    - "Cities with a population of 1,000 or greater in Metro"
    - "Cities with a population of 2,500 or greater"
    - "Cities with a population of 25,000 or greater"
    - "Cities and urban unincorporated communities in Tillamook County"
    - "Urban, unincorporated land within counties"
    - "Within urban growth boundaries"
- title: "Middle housing land division (MHLD)"
  route: "????"
  description: "Local governments must allow land divisions for middle housing development proposals"
  tags:
    - "Cities with a population of 1,000 or greater in Metro"
    - "Cities with a population of 2,500 or greater"
    - "Cities with a population of 25,000 or greater"
    - "Cities and urban unincorporated communities in Tillamook County"
    - "Urban, unincorporated land within counties"
    - "Within urban growth boundaries"
- title: "Residential design standards"
  route: "residential_design_standards"
  description: "Local governments may not apply residential design standards to certain residential development applications"
  tags:
    - "All local governments"
    - "Within urban growth boundaries"
- title: "Residential homes and facilities"
  route: "residential_homes_and_facilities"
  description: "In development. Coming soon."
- title: "Single room occupancies (SRO)"
  route: "single_room_occupancies"
  description: "In development. Coming soon."
- title: "State model housing ordinances"
  route: "state_model_housing_ordinances"
  description: "In development. Coming soon."
